openapi: 3.0.3
info:
  title: Squad-21 API
  description: Squad-21 API Documentation
  contact:
    email: email@email.com
  version: 0.0.1
servers:
  - url: http://localhost:3000/
tags:
  - name: course
    description: Tudo sobre courses.
paths:
  /courses:
    get:
      tags:
        - course
      summary: Retorna todas as courses
      description: Retorna todas as courses
      operationId: getCourses
      responses:
        '200':
          description: Todas as courses.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        '400':
          description: Invalid
    post:
      tags:
        - course
      summary: Adiciona uma nova course.
      description: Adiciona uma nova course.
      operationId: addCourse
      requestBody:
        description: Cria uma nova course.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/xml:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        '200':
          description: Course criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
            application/xml:
              schema:
                $ref: '#/components/schemas/Course'
        '404':
          description: Invalid input
  /courses/{courseId}:
    get:
      tags:
        - course
      summary: Acha uma course pelo ID
      description: Retorna uma unica course
      operationId: getCourseById
      parameters:
        - name: courseId
          in: path
          description: ID da course que deseja de retorno
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
            application/xml:
              schema:
                $ref: '#/components/schemas/Course'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
    put:
      tags:
        - course
      summary: Atualiza uma course existente
      description: Atualiza uma course existente pelo ID
      operationId: updateCourse
      parameters:
        - name: courseId
          in: path
          description: ID da course que deseja de retorno
          required: true
          schema:
            type: string
      requestBody:
        description: Atualiza uma course especifica.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/xml:
            schema:
              $ref: '#/components/schemas/Course'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
            application/xml:
              schema:
                $ref: '#/components/schemas/Course'
        '400':
          description: Invalid ID
        '404':
          description: Course not found
        '405':
          description: Validation error
    delete:
      tags:
        - course
      summary: Remove uma course
      description: Remove uma course
      operationId: deleteCourse
      parameters:
        - name: courseId
          in: path
          description: ID da course que deseja remover
          required: true
          schema:
            type: string
      responses:
        400:
          description: Invalid course ID

components:
  schemas:
    Course:
      required:
        - title
        - description
      type: object
      properties:
        title:
          type: string
          example: Básico HTML, CSS e Javascript
        description:
          type: string
          example: Aprenda na prática como trabalhar com Html, CSS e JS
        modules:
          type: array
          items:
            $ref: '#/components/schemas/Modules'
    Modules:
      required:
        - code
        - title
        - description
      type: object
      properties:
        code:
          type: string
          example: 1
        title:
          type: string
          example: Introdução
        description:
          type: string
          example: Bem vindo ao novo curso! Veja aqui o vamos aprender.
